# Generated by Django 3.0 on 2021-05-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0008_auto_20210427_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='farmers_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarMeKart.ExtPro'),
        ),
        migrations.CreateModel(
            name='Myorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default='')),
                ('price', models.IntegerField()),
                ('is_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FarMeKart.UserPro')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarMeKart.ExtPro')),
                ('vegpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarMeKart.Vegpro')),
            ],
        ),
    ]
